# Generated by Django 4.1 on 2022-08-15 12:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0002_rename_mpoly_location_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None),
        ),
    ]
