# Generated by Django 4.1 on 2022-08-16 04:38

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0003_alter_location_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='saved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=256), blank=True, size=None),
        ),
    ]
