# Generated by Django 4.1 on 2022-08-16 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0004_location_saved_at_alter_location_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='saved_at',
        ),
    ]
