# Generated by Django 4.1 on 2022-08-16 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0005_remove_location_saved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='saved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
