# Generated by Django 4.1 on 2022-08-16 05:15

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0007_alter_location_saved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='city',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=1, max_length=63),
            preserve_default=False,
        ),
    ]
