# Generated by Django 4.1 on 2022-08-16 05:19

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0008_service_city_service_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=1, max_length=63),
            preserve_default=False,
        ),
    ]
