# Generated by Django 4.1 on 2022-08-16 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0009_location_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location',
        ),
    ]
