# Generated by Django 4.1 on 2022-08-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0011_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_image',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to='service/'),
        ),
    ]
