# Generated by Django 4.1 on 2022-08-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0012_alter_service_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_category',
            name='category_image',
            field=models.ImageField(default='cat.png', upload_to='    /'),
        ),
    ]
