# Generated by Django 4.1 on 2022-08-23 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0013_alter_service_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='vendor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
