# Generated by Django 4.1 on 2022-08-23 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0015_alter_service_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='is_active',
        ),
    ]
