# Generated by Django 4.1 on 2022-08-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0016_remove_service_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
