# Generated by Django 4.1 on 2022-08-29 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0018_alter_service_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_category',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_cat', to='helper_app.service_category'),
        ),
        migrations.AlterField(
            model_name='service_category',
            name='category_image',
            field=models.ImageField(default='cat.png', upload_to='profile/'),
        ),
    ]
