# Generated by Django 4.1 on 2022-08-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0020_alter_service_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
