# Generated by Django 4.1 on 2022-08-17 13:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dyanamic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages_content',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
