# Generated by Django 4.0.7 on 2022-09-05 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book_Service',
        ),
    ]
