# Generated by Django 4.0.7 on 2022-09-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_service',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
