# Generated by Django 4.0.7 on 2022-09-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0004_book_service_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_service',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
